// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'token_response.g.dart';

@JsonSerializable()
class TokenResponseModel {
  final String securityToken;
  final String refreshToken;

  TokenResponseModel({
    required this.securityToken,
    required this.refreshToken,
  });
  factory TokenResponseModel.fromJson(Map<String, dynamic> json) {
    return _$TokenResponseModelFromJson(json);
  }

  Map<String, dynamic> toJson() {
    return _$TokenResponseModelToJson(this);
  }
}
